baseURL = 'https://wei.myecl.fr/'
languageCode = 'en-us'
title = 'Wei'
paginate = 4


[Menu]
  # Main Menu
  [[menu.Main]]
  name = "Accueil"
  url= "#"
  weight = 1
  [[menu.Main]]
  name = "WEI 2024"
  url= "wei"
  weight = 2
  [[menu.Main]]
  name = "Quinzaine d'intégration"
  url="qi"
  weight = 3
  [[menu.Main]]
  name = "L'équipe"
  url= "team"
  weight = 4
  [[menu.Main]]
  name = "Galerie"
  url= "gallery"
  weight = 5

[params]
  contactLink = "contact"
  aboutPageURL = "blog"
  copyright = "© {year} <a target=\"_blank\">Eclair</a>"
  logo = "image/logo.png"
  footerlogo = "image/logo.png"
  footerDescription = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit quia ab, natus fugiat voluptas saepe ipsum animi officiis in molestiae?"

[module]
    [[module.mounts]]
      source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
      target = "assets/js/bootstrap.bundle.min.js"